spring.application.name=exemplo2-spring-boot-turmaA

# URL de conexão de banco de dados
spring.datasource.url=jdbc:h2:mem:bancoteste

# Para o H2 funcionar no codespaces
spring.h2.console.settings.web-allow-others=true
serve.forward-headers-strategy=framework

# Configurao Spring Spring Data JPA para atualizar a estrutura
# do banco automaticamente baseado nas classes do java
spring.jpa.hibernate-ddl-auto=update